version: '3'

services:

  app:
    build: .
    container_name: portal-app
    hostname: app
    volumes:
      - .:/var/www
    networks:
      - portal-network

  nginx:
    build: .docker/nginx
    container_name: portal-nginx
    restart: on-failure
    tty: true
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    networks:
      - portal-network
    depends_on:
      - app

networks:
  portal-network:
    driver: bridge